services:
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gobank_db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      DB_SOURCE: postgresql://root:secret@postgres:5432/gobank_db?sslmode=disable
      GIN_MODE: release
    depends_on:
        - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]