# Example file, need to be updated to work in real AWS environment.

apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::760486049168:user/github-ci
      username: github-ci
      groups:
        - system:masters
